<!doctype html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Jumbotron Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="public/assets/css/style.css" rel="stylesheet">
  </head>

  <body>

    <?php require_once __DIR__ . "/menu.phtml" ?>
    <?php  ?>
    

    <script src="public/assets/js/jquery-3.2.1.min.js"></script>
    <script src="public/assets/js/bootstrap.min.js"></script>
  </body>
</html>
